name: CI Frontend FiecLab

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # Job 1: Validar e compilar o código React
  build-react:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Compilar o projeto
        run: npm run build --if-present
        env:
          CI: false

  # Job 2: Gerar e publicar a imagem Docker
  docker-build:
    runs-on: ubuntu-latest
    needs: build-react
    if: github.event_name == 'push'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            fieclab/fiecpa2026:latest
            fieclab/fiecpa2026:${{ github.sha }}

  # Job 3: Atualizar o Frontend no Minikube local
  deploy-k8s:
    runs-on: self-hosted
    needs: docker-build
    if: github.event_name == 'push'
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Aplicar manifests no Kubernetes
        run: kubectl apply -f deployment.yaml

      - name: Forçar novo rollout do frontend
        run: kubectl rollout restart deployment/frontend-deployment

      - name: Aguardar rollout concluir
        run: kubectl rollout status deployment/frontend-deployment --timeout=180s